version: "3.9"
services:
    backend:
        image: banking
        container_name: banking
        build:
            context: ./banking
        ports:
            - "8080:80"
    frontend:
        image: banking-ui
        container_name: banking-ui
        build:
            context: ./banking-fe
        ports:
            - "4200:80"
        depends_on:
            - backend