INSERT INTO TRANSACTION (ID ,AMOUNT ,CREATION_DATE ,IN_CASH ,DEST_ACCOUNT ,SOURCE_ACCOUNT ) VALUES(1,50.0, '2022-01-24',true,1,null)
INSERT INTO TRANSACTION (ID ,AMOUNT ,CREATION_DATE ,IN_CASH ,DEST_ACCOUNT ,SOURCE_ACCOUNT ) VALUES(2,150.0, '2022-01-24',true,null,2)
INSERT INTO TRANSACTION (ID ,AMOUNT ,CREATION_DATE ,IN_CASH ,DEST_ACCOUNT ,SOURCE_ACCOUNT ) VALUES(3,50.0, '2022-01-24',true,2,null)
